base: &base
  logLevels:
    - verbose
    - debug
    - log
    - warn
    - error
  pointsToWin: 10
  teams:
    - name: blue
      color: [52, 152, 219]
      points: 0
      rivalGoalPin: 16
    - name: red
      color: [231, 76, 60]
      points: 0
      rivalGoalPin: 15

development:
  <<: *base

testing:
  <<: *base
  teams: []

production:
  <<: *base
