base: &base
    logLevels:
        - verbose
        - debug
        - log
        - warn
        - error
    teams:
        - color: blue
          points: 0
          pin: 11
        - color: red
          points: 0
          pin: 13

development:
    <<: *base

production:
    <<: *base

testing:
    <<: *base
    teams: []
