base: &base
    logLevels:
        - verbose
        - debug
        - log
        - warn
        - error
    teams:
        - color: blue
          goals: 0
        - color: red
          goals: 0

development:
    <<: *base

testing:
    <<: *base
    teams: []

production:
    <<: *base
