base: &base
  logLevels:
    - verbose
    - debug
    - log
    - warn
    - error
  teams:
    - name: blue
      color: [52, 152, 219]
      points: 0
      rivalGoalPin: 16
    - name: red
      color: [231, 76, 60]
      points: 0
      rivalGoalPin: 15

development:
  <<: *base

testing:
  <<: *base
  teams:
    - name: amethyst
      color: [155, 89, 182]
      points: 7
      rivalGoalPin: 42
    - name: emerald
      color: [46, 204, 113]
      points: 8
      rivalGoalPin: 69

production:
  <<: *base
