#!/usr/bin/env bash

main() {
    local action='{ sleep 5; sudo reboot --no-wall; } &'

    if is_raspberry_pi; then
        "$action"
    else
        ssh foosball "$action"
    fi
}

. ./tasks/runner.sh
