#!/usr/bin/env bash

main() {
    case "$ENVIRONMENT" in
        'development')
            ENVIRONMENT="$ENVIRONMENT" NEST_DEBUG=true NODE_ENV="$ENVIRONMENT" npx nest start --watch
            ;;
        'production')
            printf 'LOG_FILE=%s\n\n' "$LOG_FILE"
            ENVIRONMENT="$ENVIRONMENT" LOG_FILE="$LOG_FILE" NO_COLOR='true' NODE_ENV="$ENVIRONMENT" node "$OUTPUT_FOLDER/main" &> "$LOG_FILE"
            ;;
        *)
            if [ -z "$ENVIRONMENT" ]; then
                throw 'NO_ENV' "missing ENVIRONMENT environment variable"
            else
                throw 'BAD_ENV' "unkown ENVIRONMENT: \"$ENVIRONMENT\""
            fi
            ;;
    esac
}

. ./tasks/runner.sh
