#!/usr/bin/env bash

main() {
    case "$ENVIRONMENT" in
        'development')
            ENVIRONMENT="$ENVIRONMENT" NEST_DEBUG=true NODE_ENV="$ENVIRONMENT" npx nest start --watch
            ;;
        'production')
            if ! command -v pm2 &> /dev/null; then
                throw 'NO_PM2' "missing pm2 command"
            fi

            ENVIRONMENT="$ENVIRONMENT" NODE_ENV="$ENVIRONMENT" pm2 start --name 'foosball' --wait-ready "$OUTPUT_FOLDER/main.js"
            ;;
        *)
            if [ -z "$ENVIRONMENT" ]; then
                throw 'NO_ENV' "missing ENVIRONMENT environment variable"
            else
                throw 'BAD_ENV' "unkown ENVIRONMENT: \"$ENVIRONMENT\""
            fi
            ;;
    esac
}

. ./tasks/runner.sh
