#!/usr/bin/env bash

main() {
    local action=''
    local option=$1

    case "$option" in
        '--coverage')
            action=(
                npx
                jest
                --config ./jest.json
                --coverage
                "${@:2}"
            )
            ;;
        '--debug')
            action=(
                node
                --inspect-brk
                -r 'tsconfig-paths/register'
                -r 'ts-node/register'
                'node_modules/.bin/jest'
                --runInBand
                "${@:2}"
            )
            ;;
        '--e2e')
            action=(
                npx
                jest
                --config ./test/jest-e2e.json
                --detectOpenHandles
                --forceExit
                "${@:2}"
            )
            ;;
        '--watch')
            action=(
                npx
                jest
                --config ./jest.json
                --watch
                "${@:2}"
            )
            ;;
        *)
            action=(
                npx
                jest
                --config ./jest.json
                "$@"
            )
            ;;
    esac

    ENVIRONMENT='testing' LOG_FILE="$(mktemp -t 'foosball.XXXXXXXXXX')" PORT='0' NODE_ENV='production' "${action[@]}"
}

. ./tasks/runner.sh
