#!/usr/bin/env bash

main() {
    if ! command -v tree &> /dev/null; then
        throw 'NO_TREE' "missing tree command"
    fi

    tree -d -L 2 -I 'build|coverage|node_modules' --noreport -n
    echo
}

. ./tasks/runner.sh
