#!/usr/bin/env bash
# Discards any changes and synchronizes the Raspberry
# Pi's project folder with the latests changes

main() {
	if ! is_raspberry_pi; then
		if [ -z "$UPLOAD_FOLDER" ]; then
			throw 'NO_UPLOAD_FOLDER' 'missing UPLOAD_FOLDER environment variable'
		fi

		ssh foosball "cd $UPLOAD_FOLDER && npm run $TASK"
		return "$?"
	fi

	git checkout .
	git reset .
	git clean -f
	git checkout "$DEFAULT_BRANCH"
	git pull --ff-only
}

. ./tasks/runner.sh
