#!/usr/bin/env bash

git_diff() {
	git diff --name-only "${DEFAULT_BRANCH}..."
}

git_status() {
	git status --porcelain --untracked-files | egrep -v '^\s*D' | cut -c 4-
}

main() {
    if is_raspberry_pi; then
        throw 'RPI' "cannot upload from within Raspberry Pi"
    fi

    if ! command -v fswatch &> /dev/null; then
        throw 'NO_FSWATCH' "missing fswatch command"
    fi

    if [ -z "$UPLOAD_FOLDER" ]; then
        throw 'NO_UPLOAD_FOLDER' 'missing UPLOAD_FOLDER environment variable'
    fi

    if [ -z "$UPLOAD_SERVER" ]; then
        throw 'NO_UPLOAD_SERVER' 'missing UPLOAD_SERVER environment variable'
    fi

    if [[ "$*" == *'--watch'* ]]; then
        watch | upload
    else
        sync | upload
    fi
}

sync() {
    { git_status; git_diff; } | sort | uniq
}

upload() {
    while read event; do
        if [ ! -r "$event" ]; then
            continue
        fi

        local file="${event#$PWD/}"
        local log="$(mktemp)"

        local options=(
            '--archive'
            '--ignore-times'
            "$file"
            "$UPLOAD_SERVER:$UPLOAD_FOLDER/$file"
        )

        set +e
        rsync "${options[@]}" &> "$log"
        local exit_code="$?"
        set -e

        if [ "$exit_code" = '0' ]; then
            printf '✓ %s\n' "$file"
        else
            printf '✖ %s\n' "$file"
            cat "$log"
        fi

        rm "$log"
    done
}

watch() {
    local options=(
        -e '.DS_Store'
        -e '.env'
        -e 'build'
        -e 'coverage'
        -e 'node_modules'
    )

    fswatch "${options[@]}" '.'
}

. ./tasks/runner.sh
